### ISSUE TITLE
Safely dealing with pointers

### ISSUE THREAD

**Issue by Noskcaj19** [poljar/rust-weechat#17]
There are a number of weechat functions that return pointers (when using `hook_signal` and a buffer pointer is returned).  Currently the API provides the raw c pointer without any protections.  Ideally there should be a type safe way of dealing with pointers returned by weechat.

In the case of `hook_signal`, weechat does not seem to provide any details to the callback as to what the pointer type is, so I don't see a way of fixing this with the stringly typed `signal` parameter.
However, it may be possible to wrap it in an opaque type that would contain the type information,  there would need to be a way to create custom signals for use with `hook_signal` and `hook_signal_send`.

**Comment by poljar** [comment]
It is unlikely that we're going to wrap this soundly relatively soon. So I suggest we hide this behind a `unstable` or `unsound` feature.

**Comment by poljar** [comment]
This has been fixed by https://github.com/poljar/rust-weechat/commit/d99085f31961bba94af6779f5ca90f339cedea51.
