### ISSUE TITLE
Cannot build latest version due to yanked bindgen

### ISSUE THREAD

**Issue by chrisvittal** [poljar/rust-weechat#27]
Version 0.3 depends on bindgen version 0.54.1 which has been yanked. Please consider upgrading to 0.55 or later.

**Comment by poljar** [comment]
Strangely enough, I only got the notification for this issue today. 0.3.1 was released 6 days ago so this is fixed.

Out of interest, what are you building with rust-weechat.

**Comment by chrisvittal** [comment]
Oh, alright, Thanks! 

I'm not building anything serious right now, was building NOT-IRC as an exercise, needed to make a client that I like using. Being able to reuse data types was appealing. Probably try again now that I know it's fixed. Thanks for the reply and the library!
