### ISSUE TITLE
CString and CStr unwraps

### ISSUE THREAD

**Issue by Noskcaj19** [poljar/rust-weechat#4]
Currently if a function that accepts a rust string is passed a string with a null byte the entire string will be replaced with an empty string without warning because of `unwrap_or_default`.  Similarly any function that returns a string may return an empty string if weechat returns invalid utf8.

The first problem can be solved by removing all null bytes from strings passed to the ffi.  It is lossy but stripping null bytes shouldn't (?) really be a problem.

The second problem is trickier.  There isn't necessarily a way to correct malformed utf8.  But CStr has `to_string_lossy`, which would probably be the best option.  However it returns a `Cow<str>` which would mean changing the api to return a `Cow` or to clone any `Borrowed` strs and return a `String`.

**Comment by poljar** [comment]
As for the first problem I don't see any other way either. It would be nice if there was a lossy function for this already. Is this something you run into using discord? If I remember correctly the script API ignores invalid inputs as well and just treats
them as empty strings.

We may want to avoid such a stringly typed API where it makes sense but probably not entirely.

 For the second problem: do we know that Weechat will return invalid utf-8? I guess if an user manages to put in a localvar invalid utf-8?

Can't we use `as_ref()` on the `Cow` to get a `&str` again like [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=73ed32ea9b9cc8f706eb114cfdd1e67a)?

**Comment by Noskcaj19** [comment]
I have encountered the first problem when I send nulls in discord messages, and I have added the lossy str -> CString conversion [in my fork](https://github.com/terminal-discord/rust-weechat/blob/e33a465df219316ad41c08acf0b154ed6777d205/weechat-rs/src/lib.rs#L69-L77).

From testing it seems that weechat stores strings as utf8 but does not validate them, so if you supply a localvar or probably other things you'll get back the same bytes of invalid utf8.  Probably not a common issue as the weechat docs recommend using only utf8.

As for your example, I never actually realized that works... Thanks for pointing that out, that would work very well.

If you would like, I can open a PR implementing both of those changes.

**Comment by poljar** [comment]
Go for it.

**Comment by Noskcaj19** [comment]
Turns out this might be a bit harder.  There seem to be issues with lifetimes [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8e51d089fbacfe57e5d9f52a7ff5a64f)

**Comment by poljar** [comment]
I guess that leaves us only with the option of turning it into an owned string using `to_owned`, which means copying data from Weechat to rust. That kinda sucks but I guess isn't to horrible.

**Comment by Noskcaj19** [comment]
The other option would be to return a `Cow` which would decrease the amount of cloning for most cases.  Which would you prefer?

**Comment by poljar** [comment]
Right, lets go with that instead and let people chose if they want to own the string. They can always use `as_ref()` themselves if they need to.
