### ISSUE TITLE
Hook callbacks should be closures

### ISSUE THREAD

**Issue by Noskcaj19** [poljar/rust-weechat#6]
Currently hook_command and hook_fd take function pointers for callbacks, this means that environment capturing closures can't be used.  Is there any specific reason for this or should they be changed to accept Fn types?  If so I can submit a PR implementing the changes.

Also, if closures are used is there any purpose for `callback_data`?  As far as I can tell a capturing closure can entirely replace them which would clean up the function signatures and remove the generic type.

**Comment by poljar** [comment]
There is no specific reason why the Fn type wasn't used. A PR implementing this would be great.

Can we leave the callback data there? People coming from the Weechat script API would expect it to be there. The python API for example can easily get away with partial function application to handle callback data but it's still there. 

If you do feel strongly about this you can remove it but I would prefer it to be there.

**Comment by Noskcaj19** [comment]
Now that I have some time to implement this, should the closures be stored in structs with dynamic dispatch or a generic parameter?  Generics means a lot more type arguments especially for structs [like this one](https://github.com/poljar/rust-weechat/blob/870c352226a199f498e8eb6c48318877a585ca28/weechat-rs/src/config.rs#L43). But of course dynamic dispatch isn't ideal.

On the other hand, fn-pointers still work fine...

**Comment by poljar** [comment]
I think generics like we already have would have been ideal. Are there some additional challenges to using generics with closures?

**Comment by Noskcaj19** [comment]
The only problem is it makes the signature a bit unwieldy, for example OptionPointers becomes:

```rust
pub(crate) struct OptionPointers<
    T,
    A,
    B,
    C,
    FA: Fn(&mut A, &T),
    FB: Fn(&mut B, &T),
    FC: Fn(&mut C, &T),
> {
    pub(crate) weechat_ptr: *mut t_weechat_plugin,
    pub(crate) check_cb: Option<FA>,
    pub(crate) check_cb_data: A,
    pub(crate) change_cb: Option<FB>,
    pub(crate) change_cb_data: B,
    pub(crate) delete_cb: Option<FC>,
    pub(crate) delete_cb_data: C,
    _phantom: std::marker::PhantomData<T>,
}

**Comment by poljar** [comment]
I think that should be fine, all that complexity is hidden from the users. We can battle this a little bit with type aliases.

**Comment by Noskcaj19** [comment]
Im closing this for now.  Replacing the function pointers with trait bounds lead to annotations leaking into the public api.  I don't see much point in boxing every callback because data can be passed though the callback_data arguments, it would just add unnecessary boxing.

In the future if we want to remove the callback_data, `Box<dyn Fn>` seems to be the best option.

**Comment by poljar** [comment]
I think I'm changing my mind on this one. The callbacks and the requirement for the data to have a `Default` implementation is very restrictive. Besides deciding if the callback data should be `mut` or not is also annoying.

Having closures would instead move that decision to the user. Another thing if we're going to have async callbacks for some of the Weechat stuff, like #14 suggest, we won't be able to the Weechat-like syntax anyways.

**Comment by poljar** [comment]
This has been implemented, only a couple of docs are missing.
